/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cyphersource.jewellery_software;

/**
 *
 * @author ghost
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        viewPage = new javax.swing.JPanel();
        view_display_tabbedpane = new javax.swing.JTabbedPane();
        view_overall_tab = new javax.swing.JPanel();
        view_totItem_label = new javax.swing.JLabel();
        view_totItemInp_label = new javax.swing.JLabel();
        view_totWt_label = new javax.swing.JLabel();
        view_selOrnament_dropdown = new javax.swing.JComboBox<>();
        view_totWtInp_label = new javax.swing.JLabel();
        view_datelimitbox_panel = new javax.swing.JPanel();
        view_fromDate_dropdown = new javax.swing.JComboBox<>();
        view_toDate_dropdown = new javax.swing.JComboBox<>();
        view_tablearea_scrollpane = new javax.swing.JScrollPane();
        view_tableone_table = new javax.swing.JTable();
        view_sold_tab = new javax.swing.JPanel();
        view_Balance_tab = new javax.swing.JPanel();
        view_return_tab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        viewPage.setBackground(java.awt.Color.white);

        view_display_tabbedpane.setBackground(java.awt.Color.white);
        view_display_tabbedpane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        view_display_tabbedpane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        view_overall_tab.setBackground(new java.awt.Color(255, 255, 255));
        view_overall_tab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        view_overall_tab.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        view_totItem_label.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        view_totItem_label.setText("Total no of Items  :");

        view_totItemInp_label.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        view_totItemInp_label.setText("1454");

        view_totWt_label.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        view_totWt_label.setText("Total Weight           :");

        view_selOrnament_dropdown.setBackground(new java.awt.Color(211, 211, 211));
        view_selOrnament_dropdown.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        view_selOrnament_dropdown.setForeground(new java.awt.Color(128, 128, 128));
        view_selOrnament_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Ornament", "Item1", "item2" }));
        view_selOrnament_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_selOrnament_dropdownActionPerformed(evt);
            }
        });

        view_totWtInp_label.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        view_totWtInp_label.setText("1050");

        view_datelimitbox_panel.setBackground(new java.awt.Color(255, 255, 255));
        view_datelimitbox_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        view_datelimitbox_panel.setForeground(new java.awt.Color(0, 0, 0));
        view_datelimitbox_panel.setName(""); // NOI18N

        view_fromDate_dropdown.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        view_fromDate_dropdown.setForeground(new java.awt.Color(0, 0, 0));
        view_fromDate_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "From", "Item 2", "Item 3", "Item 4" }));
        view_fromDate_dropdown.setToolTipText("");

        view_toDate_dropdown.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        view_toDate_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "To", "Item 2", "Item 3", "Item 4" }));
        view_toDate_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_toDate_dropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout view_datelimitbox_panelLayout = new javax.swing.GroupLayout(view_datelimitbox_panel);
        view_datelimitbox_panel.setLayout(view_datelimitbox_panelLayout);
        view_datelimitbox_panelLayout.setHorizontalGroup(
            view_datelimitbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_datelimitbox_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_fromDate_dropdown, 0, 126, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(view_toDate_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        view_datelimitbox_panelLayout.setVerticalGroup(
            view_datelimitbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_datelimitbox_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(view_datelimitbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_fromDate_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_toDate_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        view_tableone_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Date", "Chase No", "Ornamant Name", "WT", "WAS", "MC", "BARCODE", "RP"
            }
        ));
        view_tableone_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        view_tableone_table.setCellSelectionEnabled(true);
        view_tableone_table.setRowHeight(40);
        view_tableone_table.setRowMargin(0);
        view_tableone_table.setShowGrid(true);
        view_tableone_table.setShowHorizontalLines(false);
        view_tablearea_scrollpane.setViewportView(view_tableone_table);
        view_tableone_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (view_tableone_table.getColumnModel().getColumnCount() > 0) {
            view_tableone_table.getColumnModel().getColumn(0).setMinWidth(45);
            view_tableone_table.getColumnModel().getColumn(0).setPreferredWidth(45);
            view_tableone_table.getColumnModel().getColumn(0).setMaxWidth(45);
            view_tableone_table.getColumnModel().getColumn(1).setMinWidth(70);
            view_tableone_table.getColumnModel().getColumn(1).setPreferredWidth(70);
            view_tableone_table.getColumnModel().getColumn(1).setMaxWidth(70);
            view_tableone_table.getColumnModel().getColumn(2).setMinWidth(100);
            view_tableone_table.getColumnModel().getColumn(2).setPreferredWidth(100);
            view_tableone_table.getColumnModel().getColumn(2).setMaxWidth(100);
            view_tableone_table.getColumnModel().getColumn(3).setMinWidth(160);
            view_tableone_table.getColumnModel().getColumn(3).setPreferredWidth(160);
            view_tableone_table.getColumnModel().getColumn(3).setMaxWidth(160);
            view_tableone_table.getColumnModel().getColumn(4).setMinWidth(60);
            view_tableone_table.getColumnModel().getColumn(4).setPreferredWidth(60);
            view_tableone_table.getColumnModel().getColumn(4).setMaxWidth(60);
            view_tableone_table.getColumnModel().getColumn(5).setMinWidth(60);
            view_tableone_table.getColumnModel().getColumn(5).setPreferredWidth(60);
            view_tableone_table.getColumnModel().getColumn(5).setMaxWidth(60);
            view_tableone_table.getColumnModel().getColumn(6).setMinWidth(60);
            view_tableone_table.getColumnModel().getColumn(6).setPreferredWidth(60);
            view_tableone_table.getColumnModel().getColumn(6).setMaxWidth(60);
            view_tableone_table.getColumnModel().getColumn(7).setMinWidth(140);
            view_tableone_table.getColumnModel().getColumn(7).setPreferredWidth(140);
            view_tableone_table.getColumnModel().getColumn(7).setMaxWidth(140);
            view_tableone_table.getColumnModel().getColumn(8).setMinWidth(60);
            view_tableone_table.getColumnModel().getColumn(8).setPreferredWidth(60);
            view_tableone_table.getColumnModel().getColumn(8).setMaxWidth(60);
        }

        javax.swing.GroupLayout view_overall_tabLayout = new javax.swing.GroupLayout(view_overall_tab);
        view_overall_tab.setLayout(view_overall_tabLayout);
        view_overall_tabLayout.setHorizontalGroup(
            view_overall_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_overall_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(view_overall_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(view_totWt_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_totItem_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(view_overall_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(view_totItemInp_label, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(view_totWtInp_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(view_selOrnament_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_datelimitbox_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(view_tablearea_scrollpane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        view_overall_tabLayout.setVerticalGroup(
            view_overall_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_overall_tabLayout.createSequentialGroup()
                .addGroup(view_overall_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_overall_tabLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(view_selOrnament_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(view_overall_tabLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(view_overall_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(view_totItem_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_totItemInp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(view_overall_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(view_totWt_label, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(view_totWtInp_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(view_overall_tabLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(view_datelimitbox_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(view_tablearea_scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
        );

        view_display_tabbedpane.addTab("Overall", view_overall_tab);

        javax.swing.GroupLayout view_sold_tabLayout = new javax.swing.GroupLayout(view_sold_tab);
        view_sold_tab.setLayout(view_sold_tabLayout);
        view_sold_tabLayout.setHorizontalGroup(
            view_sold_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        view_sold_tabLayout.setVerticalGroup(
            view_sold_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        view_display_tabbedpane.addTab("Sold", view_sold_tab);

        javax.swing.GroupLayout view_Balance_tabLayout = new javax.swing.GroupLayout(view_Balance_tab);
        view_Balance_tab.setLayout(view_Balance_tabLayout);
        view_Balance_tabLayout.setHorizontalGroup(
            view_Balance_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        view_Balance_tabLayout.setVerticalGroup(
            view_Balance_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        view_display_tabbedpane.addTab("Balance", view_Balance_tab);

        javax.swing.GroupLayout view_return_tabLayout = new javax.swing.GroupLayout(view_return_tab);
        view_return_tab.setLayout(view_return_tabLayout);
        view_return_tabLayout.setHorizontalGroup(
            view_return_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        view_return_tabLayout.setVerticalGroup(
            view_return_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        view_display_tabbedpane.addTab("Return", view_return_tab);

        javax.swing.GroupLayout viewPageLayout = new javax.swing.GroupLayout(viewPage);
        viewPage.setLayout(viewPageLayout);
        viewPageLayout.setHorizontalGroup(
            viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPageLayout.createSequentialGroup()
                .addComponent(view_display_tabbedpane, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        viewPageLayout.setVerticalGroup(
            viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(view_display_tabbedpane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLayeredPane1.add(viewPage, "viewPage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_selOrnament_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_selOrnament_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_selOrnament_dropdownActionPerformed

    private void view_toDate_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_toDate_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_toDate_dropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel viewPage;
    private javax.swing.JPanel view_Balance_tab;
    private javax.swing.JPanel view_datelimitbox_panel;
    private javax.swing.JTabbedPane view_display_tabbedpane;
    private javax.swing.JComboBox<String> view_fromDate_dropdown;
    private javax.swing.JPanel view_overall_tab;
    private javax.swing.JPanel view_return_tab;
    private javax.swing.JComboBox<String> view_selOrnament_dropdown;
    private javax.swing.JPanel view_sold_tab;
    private javax.swing.JScrollPane view_tablearea_scrollpane;
    private javax.swing.JTable view_tableone_table;
    private javax.swing.JComboBox<String> view_toDate_dropdown;
    private javax.swing.JLabel view_totItemInp_label;
    private javax.swing.JLabel view_totItem_label;
    private javax.swing.JLabel view_totWtInp_label;
    private javax.swing.JLabel view_totWt_label;
    // End of variables declaration//GEN-END:variables

  public class Table_header extends javax.swing.JFrame{
      
  }


}
